matrix:
  include:
    - language: java
      script: 
        - cd service/Services && mvn install -Dmaven.test.skip=true   && cd ../Cloud-Config && mvn install -Dmaven.test.skip=true && cd ../eureka-service && mvn install -Dmaven.test.skip=true && cd ../../dashboard && mvn install -Dmaven.test.skip=true && cd ../ui && mvn install -Dmaven.test.skip=true && cd ../scheduler/SchedulerService && mvn install -Dmaven.test.skip=true && cd ../../jenkins/custom_tools/DevopsJsonConv && mvn install -Dmaven.test.skip=true && cd ../MetricsProcessor && mvn install -Dmaven.test.skip=true && cd ../ReportFetchUtil && mvn install -Dmaven.test.skip=true && cd ../SchedulerUtility && mvn install -Dmaven.test.skip=true && cd ../../../subscription && mvn install -Dmaven.test.skip=true
    - language: groovy
      addons:
        sonarcloud:
        organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
        before script:
          - cd dsl
        script:
          - gradle build && cd .. && sonar-scanner
  
