//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.20 at 12:10:20 PM IST 
//
package com.infosys.utilities.ntrxunit;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public TestRun createTestRun() {
		return new TestRun();
	}

	public TestRun.Results createTestRunResults() {
		return new TestRun.Results();
	}

	public TestRun.TestEntries createTestRunTestEntries() {
		return new TestRun.TestEntries();
	}

	public TestRun.TestLists createTestRunTestLists() {
		return new TestRun.TestLists();
	}

	public TestRun.TestDefinitions createTestRunTestDefinitions() {
		return new TestRun.TestDefinitions();
	}

	public TestRun.TestDefinitions.UnitTest createTestRunTestDefinitionsUnitTest() {
		return new TestRun.TestDefinitions.UnitTest();
	}

	public TestRun.ResultSummary createTestRunResultSummary() {
		return new TestRun.ResultSummary();
	}

	public TestRun.ResultSummary.ResultFiles createTestRunResultSummaryResultFiles() {
		return new TestRun.ResultSummary.ResultFiles();
	}

	public TestRun.ResultSummary.RunInfos createTestRunResultSummaryRunInfos() {
		return new TestRun.ResultSummary.RunInfos();
	}

	public TestRun.TestSettings createTestRunTestSettings() {
		return new TestRun.TestSettings();
	}

	public TestRun.TestSettings.Execution createTestRunTestSettingsExecution() {
		return new TestRun.TestSettings.Execution();
	}

	public TestRun.TestSettings.Execution.AgentRule createTestRunTestSettingsExecutionAgentRule() {
		return new TestRun.TestSettings.Execution.AgentRule();
	}

	public TestRun.TestSettings.Execution.AgentRule.DataCollectors createTestRunTestSettingsExecutionAgentRuleDataCollectors() {
		return new TestRun.TestSettings.Execution.AgentRule.DataCollectors();
	}

	public TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector createTestRunTestSettingsExecutionAgentRuleDataCollectorsDataCollector() {
		return new TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector();
	}

	public TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration createTestRunTestSettingsExecutionAgentRuleDataCollectorsDataCollectorConfiguration() {
		return new TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration();
	}

	public TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration.CodeCoverage createTestRunTestSettingsExecutionAgentRuleDataCollectorsDataCollectorConfigurationCodeCoverage() {
		return new TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration.CodeCoverage();
	}

	public TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration.CodeCoverage.Regular createTestRunTestSettingsExecutionAgentRuleDataCollectorsDataCollectorConfigurationCodeCoverageRegular() {
		return new TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration.CodeCoverage.Regular();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific createTestRunTestSettingsExecutionTestTypeSpecific() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration createTestRunTestSettingsExecutionTestTypeSpecificWebTestRunConfiguration() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration.Browser createTestRunTestSettingsExecutionTestTypeSpecificWebTestRunConfigurationBrowser() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration.Browser();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration.Browser.Headers createTestRunTestSettingsExecutionTestTypeSpecificWebTestRunConfigurationBrowserHeaders() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration.Browser.Headers();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific.UnitTestRunConfig createTestRunTestSettingsExecutionTestTypeSpecificUnitTestRunConfig() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific.UnitTestRunConfig();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific.UnitTestRunConfig.AssemblyResolution createTestRunTestSettingsExecutionTestTypeSpecificUnitTestRunConfigAssemblyResolution() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific.UnitTestRunConfig.AssemblyResolution();
	}

	public TestRun.Times createTestRunTimes() {
		return new TestRun.Times();
	}

	public TestRun.Results.UnitTestResult createTestRunResultsUnitTestResult() {
		return new TestRun.Results.UnitTestResult();
	}

	public TestRun.TestEntries.TestEntry createTestRunTestEntriesTestEntry() {
		return new TestRun.TestEntries.TestEntry();
	}

	public TestRun.TestLists.TestList createTestRunTestListsTestList() {
		return new TestRun.TestLists.TestList();
	}

	public TestRun.TestDefinitions.UnitTest.Execution createTestRunTestDefinitionsUnitTestExecution() {
		return new TestRun.TestDefinitions.UnitTest.Execution();
	}

	public TestRun.TestDefinitions.UnitTest.TestMethod createTestRunTestDefinitionsUnitTestTestMethod() {
		return new TestRun.TestDefinitions.UnitTest.TestMethod();
	}

	public TestRun.ResultSummary.Counters createTestRunResultSummaryCounters() {
		return new TestRun.ResultSummary.Counters();
	}

	public TestRun.ResultSummary.ResultFiles.ResultFile createTestRunResultSummaryResultFilesResultFile() {
		return new TestRun.ResultSummary.ResultFiles.ResultFile();
	}

	public TestRun.ResultSummary.RunInfos.RunInfo createTestRunResultSummaryRunInfosRunInfo() {
		return new TestRun.ResultSummary.RunInfos.RunInfo();
	}

	public TestRun.TestSettings.Deployment createTestRunTestSettingsDeployment() {
		return new TestRun.TestSettings.Deployment();
	}

	public TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration.CodeCoverage.Regular.CodeCoverageItem createTestRunTestSettingsExecutionAgentRuleDataCollectorsDataCollectorConfigurationCodeCoverageRegularCodeCoverageItem() {
		return new TestRun.TestSettings.Execution.AgentRule.DataCollectors.DataCollector.Configuration.CodeCoverage.Regular.CodeCoverageItem();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration.Browser.Headers.Header createTestRunTestSettingsExecutionTestTypeSpecificWebTestRunConfigurationBrowserHeadersHeader() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific.WebTestRunConfiguration.Browser.Headers.Header();
	}

	public TestRun.TestSettings.Execution.TestTypeSpecific.UnitTestRunConfig.AssemblyResolution.TestDirectory createTestRunTestSettingsExecutionTestTypeSpecificUnitTestRunConfigAssemblyResolutionTestDirectory() {
		return new TestRun.TestSettings.Execution.TestTypeSpecific.UnitTestRunConfig.AssemblyResolution.TestDirectory();
	}
}
