//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.13 at 02:08:44 PM IST 
//
package com.infosys.utilities.fxcopreport;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public FxCopReport createFxCopReport() {
		return new FxCopReport();
	}

	public FxCopReport.Exceptions createFxCopReportExceptions() {
		return new FxCopReport.Exceptions();
	}

	public FxCopReport.Localized createFxCopReportLocalized() {
		return new FxCopReport.Localized();
	}

	public FxCopReport.Rules createFxCopReportRules() {
		return new FxCopReport.Rules();
	}

	public FxCopReport.Rules.Rule createFxCopReportRulesRule() {
		return new FxCopReport.Rules.Rule();
	}

	public FxCopReport.Targets createFxCopReportTargets() {
		return new FxCopReport.Targets();
	}

	public FxCopReport.Targets.Target createFxCopReportTargetsTarget() {
		return new FxCopReport.Targets.Target();
	}

	public FxCopReport.Targets.Target.Modules createFxCopReportTargetsTargetModules() {
		return new FxCopReport.Targets.Target.Modules();
	}

	public FxCopReport.Targets.Target.Modules.Module createFxCopReportTargetsTargetModulesModule() {
		return new FxCopReport.Targets.Target.Modules.Module();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces createFxCopReportTargetsTargetModulesModuleNamespaces() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace createFxCopReportTargetsTargetModulesModuleNamespacesNamespace() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypes() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesType() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembers() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMember() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberAccessors() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberAccessorsAccessor() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor.Messages createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberAccessorsAccessorMessages() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor.Messages();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor.Messages.Message createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberAccessorsAccessorMessagesMessage() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor.Messages.Message();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Messages createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberMessages() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Messages();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Messages.Message createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberMessagesMessage() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Messages.Message();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Messages createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMessages() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Messages();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Messages.Message createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMessagesMessage() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Messages.Message();
	}

	public FxCopReport.Targets.Target.Modules.Module.Messages createFxCopReportTargetsTargetModulesModuleMessages() {
		return new FxCopReport.Targets.Target.Modules.Module.Messages();
	}

	public FxCopReport.Targets.Target.Modules.Module.Messages.Message createFxCopReportTargetsTargetModulesModuleMessagesMessage() {
		return new FxCopReport.Targets.Target.Modules.Module.Messages.Message();
	}

	public FxCopReport.Exceptions.Exception createFxCopReportExceptionsException() {
		return new FxCopReport.Exceptions.Exception();
	}

	public FxCopReport.Localized.String createFxCopReportLocalizedString() {
		return new FxCopReport.Localized.String();
	}

	public FxCopReport.Rules.Rule.Resolution createFxCopReportRulesRuleResolution() {
		return new FxCopReport.Rules.Rule.Resolution();
	}

	public FxCopReport.Rules.Rule.MessageLevel createFxCopReportRulesRuleMessageLevel() {
		return new FxCopReport.Rules.Rule.MessageLevel();
	}

	public FxCopReport.Rules.Rule.File createFxCopReportRulesRuleFile() {
		return new FxCopReport.Rules.Rule.File();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor.Messages.Message.Issue createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberAccessorsAccessorMessagesMessageIssue() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Accessors.Accessor.Messages.Message.Issue();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Messages.Message.Issue createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMembersMemberMessagesMessageIssue() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Members.Member.Messages.Message.Issue();
	}

	public FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Messages.Message.Issue createFxCopReportTargetsTargetModulesModuleNamespacesNamespaceTypesTypeMessagesMessageIssue() {
		return new FxCopReport.Targets.Target.Modules.Module.Namespaces.Namespace.Types.Type.Messages.Message.Issue();
	}

	public FxCopReport.Targets.Target.Modules.Module.Messages.Message.Issue createFxCopReportTargetsTargetModulesModuleMessagesMessageIssue() {
		return new FxCopReport.Targets.Target.Modules.Module.Messages.Message.Issue();
	}
}
