//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.09 at 05:31:15 PM IST 
//
package com.infosys.utilities.findbugs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {
	private final static QName _BugCollectionBugInstanceField_QNAME = new QName("", "Field");
	private final static QName _BugCollectionBugInstanceLongMessage_QNAME = new QName("", "LongMessage");
	private final static QName _BugCollectionBugInstanceMethod_QNAME = new QName("", "Method");
	private final static QName _BugCollectionBugInstanceString_QNAME = new QName("", "String");
	private final static QName _BugCollectionBugInstanceType_QNAME = new QName("", "Type");
	private final static QName _BugCollectionBugInstanceClass_QNAME = new QName("", "Class");
	private final static QName _BugCollectionBugInstanceProperty_QNAME = new QName("", "Property");
	private final static QName _BugCollectionBugInstanceInt_QNAME = new QName("", "Int");
	private final static QName _BugCollectionBugInstanceLocalVariable_QNAME = new QName("", "LocalVariable");
	private final static QName _BugCollectionBugInstanceSourceLine_QNAME = new QName("", "SourceLine");
	private final static QName _BugCollectionBugInstanceShortMessage_QNAME = new QName("", "ShortMessage");
	private final static QName _BugCollectionBugInstanceMethodSourceLineMessage_QNAME = new QName("", "Message");

	public BugCollection createBugCollection() {
		return new BugCollection();
	}

	public BugCollection.BugInstance.Int createBugCollectionBugInstanceInt() {
		return new BugCollection.BugInstance.Int();
	}

	public BugCollection.BugInstance.Field createBugCollectionBugInstanceField() {
		return new BugCollection.BugInstance.Field();
	}

	public BugCollection.BugCode createBugCollectionBugCode() {
		return new BugCollection.BugCode();
	}

	public BugCollection.FindBugsSummary.PackageStats createBugCollectionFindBugsSummaryPackageStats() {
		return new BugCollection.FindBugsSummary.PackageStats();
	}

	public BugCollection.BugInstance.String createBugCollectionBugInstanceString() {
		return new BugCollection.BugInstance.String();
	}

	public BugCollection.Project createBugCollectionProject() {
		return new BugCollection.Project();
	}

	public BugCollection.BugInstance.Class.SourceLine createBugCollectionBugInstanceClassSourceLine() {
		return new BugCollection.BugInstance.Class.SourceLine();
	}

	public BugCollection.FindBugsSummary.FindBugsProfile.ClassProfile createBugCollectionFindBugsSummaryFindBugsProfileClassProfile() {
		return new BugCollection.FindBugsSummary.FindBugsProfile.ClassProfile();
	}

	public BugCollection.BugInstance.Type createBugCollectionBugInstanceType() {
		return new BugCollection.BugInstance.Type();
	}

	public BugCollection.FindBugsSummary.PackageStats.ClassStats createBugCollectionFindBugsSummaryPackageStatsClassStats() {
		return new BugCollection.FindBugsSummary.PackageStats.ClassStats();
	}

	public BugCollection.BugPattern createBugCollectionBugPattern() {
		return new BugCollection.BugPattern();
	}

	public BugCollection.BugInstance.Method createBugCollectionBugInstanceMethod() {
		return new BugCollection.BugInstance.Method();
	}

	public BugCollection.FindBugsSummary.FileStats createBugCollectionFindBugsSummaryFileStats() {
		return new BugCollection.FindBugsSummary.FileStats();
	}

	public BugCollection.FindBugsSummary.FindBugsProfile createBugCollectionFindBugsSummaryFindBugsProfile() {
		return new BugCollection.FindBugsSummary.FindBugsProfile();
	}

	public BugCollection.BugInstance.LocalVariable createBugCollectionBugInstanceLocalVariable() {
		return new BugCollection.BugInstance.LocalVariable();
	}

	public BugCollection.FindBugsSummary createBugCollectionFindBugsSummary() {
		return new BugCollection.FindBugsSummary();
	}

	public BugCollection.Errors createBugCollectionErrors() {
		return new BugCollection.Errors();
	}

	public BugCollection.BugCategory createBugCollectionBugCategory() {
		return new BugCollection.BugCategory();
	}

	public BugCollection.BugInstance.Class createBugCollectionBugInstanceClass() {
		return new BugCollection.BugInstance.Class();
	}

	public BugCollection.BugInstance.Field.SourceLine createBugCollectionBugInstanceFieldSourceLine() {
		return new BugCollection.BugInstance.Field.SourceLine();
	}

	public BugCollection.BugInstance createBugCollectionBugInstance() {
		return new BugCollection.BugInstance();
	}

	public BugCollection.BugInstance.Type.SourceLine createBugCollectionBugInstanceTypeSourceLine() {
		return new BugCollection.BugInstance.Type.SourceLine();
	}

	public BugCollection.BugInstance.Property createBugCollectionBugInstanceProperty() {
		return new BugCollection.BugInstance.Property();
	}

	public BugCollection.BugInstance.Method.SourceLine createBugCollectionBugInstanceMethodSourceLine() {
		return new BugCollection.BugInstance.Method.SourceLine();
	}

	public BugCollection.BugInstance.SourceLine createBugCollectionBugInstanceSourceLine() {
		return new BugCollection.BugInstance.SourceLine();
	}

	@XmlElementDecl(namespace = "", name = "Field", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.Field> createBugCollectionBugInstanceField(
			BugCollection.BugInstance.Field value) {
		return new JAXBElement<BugCollection.BugInstance.Field>(_BugCollectionBugInstanceField_QNAME,
				BugCollection.BugInstance.Field.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "LongMessage", scope = BugCollection.BugInstance.class)
	public JAXBElement<java.lang.String> createBugCollectionBugInstanceLongMessage(java.lang.String value) {
		return new JAXBElement<java.lang.String>(_BugCollectionBugInstanceLongMessage_QNAME, java.lang.String.class,
				BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "Method", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.Method> createBugCollectionBugInstanceMethod(
			BugCollection.BugInstance.Method value) {
		return new JAXBElement<BugCollection.BugInstance.Method>(_BugCollectionBugInstanceMethod_QNAME,
				BugCollection.BugInstance.Method.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "String", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.String> createBugCollectionBugInstanceString(
			BugCollection.BugInstance.String value) {
		return new JAXBElement<BugCollection.BugInstance.String>(_BugCollectionBugInstanceString_QNAME,
				BugCollection.BugInstance.String.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "Type", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.Type> createBugCollectionBugInstanceType(
			BugCollection.BugInstance.Type value) {
		return new JAXBElement<BugCollection.BugInstance.Type>(_BugCollectionBugInstanceType_QNAME,
				BugCollection.BugInstance.Type.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "Class", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.Class> createBugCollectionBugInstanceClass(
			BugCollection.BugInstance.Class value) {
		return new JAXBElement<BugCollection.BugInstance.Class>(_BugCollectionBugInstanceClass_QNAME,
				BugCollection.BugInstance.Class.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "Property", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.Property> createBugCollectionBugInstanceProperty(
			BugCollection.BugInstance.Property value) {
		return new JAXBElement<BugCollection.BugInstance.Property>(_BugCollectionBugInstanceProperty_QNAME,
				BugCollection.BugInstance.Property.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "Int", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.Int> createBugCollectionBugInstanceInt(
			BugCollection.BugInstance.Int value) {
		return new JAXBElement<BugCollection.BugInstance.Int>(_BugCollectionBugInstanceInt_QNAME,
				BugCollection.BugInstance.Int.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "LocalVariable", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.LocalVariable> createBugCollectionBugInstanceLocalVariable(
			BugCollection.BugInstance.LocalVariable value) {
		return new JAXBElement<BugCollection.BugInstance.LocalVariable>(_BugCollectionBugInstanceLocalVariable_QNAME,
				BugCollection.BugInstance.LocalVariable.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "SourceLine", scope = BugCollection.BugInstance.class)
	public JAXBElement<BugCollection.BugInstance.SourceLine> createBugCollectionBugInstanceSourceLine(
			BugCollection.BugInstance.SourceLine value) {
		return new JAXBElement<BugCollection.BugInstance.SourceLine>(_BugCollectionBugInstanceSourceLine_QNAME,
				BugCollection.BugInstance.SourceLine.class, BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "ShortMessage", scope = BugCollection.BugInstance.class)
	public JAXBElement<java.lang.String> createBugCollectionBugInstanceShortMessage(java.lang.String value) {
		return new JAXBElement<java.lang.String>(_BugCollectionBugInstanceShortMessage_QNAME, java.lang.String.class,
				BugCollection.BugInstance.class, value);
	}

	@XmlElementDecl(namespace = "", name = "Message", scope = BugCollection.BugInstance.Method.SourceLine.class)
	public JAXBElement<java.lang.String> createBugCollectionBugInstanceMethodSourceLineMessage(java.lang.String value) {
		return new JAXBElement<java.lang.String>(_BugCollectionBugInstanceMethodSourceLineMessage_QNAME,
				java.lang.String.class, BugCollection.BugInstance.Method.SourceLine.class, value);
	}
}
